### ISSUE TITLE
Unable to resolve 'System.Net.Http

### ISSUE THREAD

**Issue by sita-egypt** [SPSphinx/Egyptian-eInvoicing-eSeal-Solution#1]
We are getting

C:\Users\resmat\Desktop\Egyptian-eInvoicing-eSeal-Solution-main\MiddlewareLibraryCore\MiddlewareLibraryCore.csproj : error NU1100: Unable to resolve 'System.Net.Http 
(>= 4.3.4)' for 'net5.0'. [C:\Users\resmat\Desktop\Egyptian-eInvoicing-eSeal-Solution-main\MiddlewareConsoleCore\MiddlewareConsoleCore.csproj]

C:\Users\resmat\Desktop\Egyptian-eInvoicing-eSeal-Solution-main\MiddlewareConsoleCore\MiddlewareConsoleCore.csproj : error NU1100: Unable to resolve 'System.Net.Http 
(>= 4.3.4)' for 'net5.0'.

The build failed. Fix the build errors and run again.

"Build Tools for Visual Studio 1.57" plus .NET Core 5.0.301 SDK installed

**Comment by SPSphinx** [comment]
Please explain the Visual Studio and .NET framework versions.

**Comment by sita-egypt** [comment]
@SPSphinx thank you so much it's working now.

**Comment by SPSphinx** [comment]
Good luck
